<?php
/**
 * Auto generated by prado-cli.php on 2009-01-30 09:34:08.
 */
class ProfileRecord extends TActiveRecord
{
	const TABLE='sys_seg_perfiles';

	public $sys_seg_perfiles_id;
	public $nombre_perfil;
	public $estado;
	
	public static $RELATIONS=array
    (
        'Usuarios' => array(self::MANY_TO_MANY, 'UserRecord', 'sys_seg_usuarios_has_perfiles'),
    );

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>