<?php
/**
 * Auto generated by prado-cli.php on 2009-01-30 09:34:43.
 */
class SubModuloRecord extends TActiveRecord
{
	const TABLE='sys_seg_submodulos';

	public $sys_seg_submodulos_id;
	public $sys_seg_modulos_id;
	public $nombre_submodulo;
	public $estado;

	public static $RELATIONS=array
	(
		'modulo' => array(self::BELONGS_TO, 'ModuloRecord', 'sys_seg_modulos_id'),
	);

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}

}
?>