<?php
/**
 * Auto generated by prado-cli.php on 2009-01-30 09:53:41.
 */
class UserRecord extends TActiveRecord
{
	const TABLE='sys_seg_usuarios';

	public $sys_seg_usuarios_id;
	public $login;
	public $password;
	public $nombres;
	public $apellidos;
	public $email;
	public $estado;
	public $last_login;
	
	
	public static $RELATIONS=array
    (
        'Perfiles' => array(self::MANY_TO_MANY, 'ProfileRecord', 'sys_seg_usuarios_has_perfiles'),
        'Recursos' => array(self::MANY_TO_MANY, 'RecursoRecord', 'sys_seg_usuarios_has_recursos_view'),
    );

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>