<?php
/**
 * Auto generated by prado-cli.php on 2009-01-30 09:53:41.
 */
class SistemaRecord extends TActiveRecord
{
	const TABLE='configuracion_sistema';

	public $configuracion_sistema_id;
	public $email_administrador;
	public $dominio_aplicacion;
	public $direccion_ip_camara;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>