<?php
/**
 * Auto generated by prado-cli.php on 2009-01-30 09:35:26.
 */
class FuncionRecord extends TActiveRecord
{
	const TABLE='sys_seg_funciones';

	public $sys_seg_funciones_id;
	public $sys_seg_submodulos_id;
	public $nombre_funcion;
	public $visible_menu;
	public $estado;
	
	public static $RELATIONS=array
	(
		'submodulo' => array(self::BELONGS_TO, 'SubModuloRecord', 'sys_seg_submodulos_id'),
	);

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>