<?php
/**
 * Auto generated by prado-cli.php on 2009-01-30 09:34:29.
 */
class ModuloRecord extends TActiveRecord
{
	const TABLE='sys_seg_modulos';

	public $sys_seg_modulos_id;
	public $nombre_modulo;
	public $estado;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
	
	public static $RELATIONS=array
    (
        'SubModulos' => array(self::HAS_MANY, 'SubModuloRecord'),
    );
}
?>